site_name: ClearDocs
site_url: https://cleardocs.dev/
site_description: Clear technical writing on software, developer docs, and modern science. Tutorials, guides, and insights made simple.

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.follow
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo

nav:
  - Home: index.md
  - About: about.md
  - Manifesto: manifesto.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite

plugins:
  - search